@startuml
hide empty methods
hide empty attributes

title MESSless Domain Layer Model
note "All fields not marked with <<nullable>> are not nullable" as NullConvention

entity User<Entity> {
  email: Email
  password: Password <<encrypted>>
  role: UserRole
  phone: String
  firstName: String
  lastName: String
  ---
  createdAt: Timestamp
  updatedAt: Timestamp <<nullable>>
  deletedAt: Timestamp <<nullable>>
}

enum UserRole {
  Admin
  CompanyAdmin
  Manager
  Worker
  StageHand
}

entity Loggable {
  label: String
  location: Point
  loggableType: LoggableType
  companyId: Company
  ---
  createdAt: Timestamp
  updatedAt: Timestamp <<nullable>>
  deletedAt: Timestamp <<nullable>>
}

entity Warehouse<Entity> {
  loggable: Loggable
}

entity Event<Entity> {
  loggable: Loggable
}

entity EquipmentStorage<Entity> {
  loggable: Loggable
}

entity Equipment<Entity> {
  label: String
  belongsTo: Warehouse
  isStorage: EquipmentStorage?
  ---
  createdAt: Timestamp
  updatedAt: Timestamp <<nullable>>
  deletedAt: Timestamp <<nullable>>
}

entity Company<Entity> {
  label: String
  location: Point
  warehouses: Warehouse[]
  employees: User[]
  ---
  createdAt: Timestamp
  updatedAt: Timestamp <<nullable>>
  deletedAt: Timestamp <<nullable>>
}

entity TechnicalLogEntry<Entity> {
  attachedTo: Equipment
  loggable: Loggable
  by: User
  isCheckIn: bool
  ---
  createdAt: Timestamp
  updatedAt: Timestamp <<nullable>>
  deletedAt: Timestamp <<nullable>>
}

enum LoggableType {
    Warehouse,
    Event,
    EquipmentStorage
}

' relations
TechnicalLogEntry --> Equipment
TechnicalLogEntry --> Loggable
TechnicalLogEntry -right-> User

Loggable -left-> LoggableType
Loggable --up* Company

Warehouse --left* Loggable
Event --up* Loggable
EquipmentStorage --down* Loggable

Equipment --> EquipmentStorage

Equipment ---> Warehouse

User --right> UserRole

Warehouse --right* Company
User --down* Company

@enduml