@startuml
hide empty methods
hide empty attributes

title MESSless Domain Layer Model
note "All fields not marked with <<nullable>> are not nullable" as NullConvention

entity User<Entity> {
  email: Email
  password: Password <<encrypted>>
  role: UserRole
  phone: String
  firstName: String
  lastName: String
  ---
  createdAt: Timestamp
  updatedAt: Timestamp <<nullable>>
  deletedAt: Timestamp <<nullable>>
}

entity EmployedAtEvent {
  user: User
  event : Event
}

enum UserRole {
  Admin
  CompanyAdmin
  Manager
  Worker
  StageHand
}

abstract Loggable<Abstract> {
  label: String
  location: Location
  ---
  createdAt: Timestamp
  updatedAt: Timestamp <<nullable>>
  deletedAt: Timestamp <<nullable>>
}

entity Warehouse<Entity> {
  belongsTo: Company
}

entity Event<Entity> {
}

entity Equipment<Entity> {
  label: String
  location: Location
  belongsTo: Warehouse
  ---
  createdAt: Timestamp
  updatedAt: Timestamp <<nullable>>
  deletedAt: Timestamp <<nullable>>
}

entity Company<Entity> {
  label: String
  location: Location
  ownedBy: User
  ---
  createdAt: Timestamp
  updatedAt: Timestamp <<nullable>>
  deletedAt: Timestamp <<nullable>>
}

entity TechnicalLogEntry<Entity> {
  attachedTo: Equipment
  loggable: Loggable
  ---
  createdAt: Timestamp
  updatedAt: Timestamp <<nullable>>
  deletedAt: Timestamp <<nullable>>
}

entity Location <Value Object> <<(V, EEAAEE), embeddable>> {
  lat: float
  long: float
}

' relations
User -down-> UserRole
EmployedAtEvent -left-> User
EmployedAtEvent -right-> Event
Company -down-> User

Equipment -down-> Location
TechnicalLogEntry --> Equipment
TechnicalLogEntry --> Loggable

Loggable --|> Warehouse
Loggable --|> Event

Equipment ---> Warehouse
@enduml